### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'base_model_name_or_path'

### ISSUE THREAD

**Issue by Addss-s** [rui-ye/OpenFedLLM#35]
May I ask what happened to this error

**Comment by rui-ye** [comment]
Please provide more details

**Comment by Addss-s** [comment]
Traceback (most recent call last):
  File "/home/lias/OpenFedLLM-main/main_dpo.py", line 61, in <module>
    model = get_peft_model(model, peft_config)
  File "/home/lias/yes/envs/opfl/lib/python3.9/site-packages/peft/mapping.py", line 90, in get_peft_model
    peft_config.base_model_name_or_path = model.__dict__.get("name_or_path", None)
AttributeError: 'NoneType' object has no attribute 'base_model_name_or_path'

**Comment by Addss-s** [comment]
> 请提供更多详细信息

Traceback (most recent call last):
File "/home/lias/OpenFedLLM-main/main_dpo.py", line 61, in
model = get_peft_model(model, peft_config)
File "/home/lias/yes/envs/opfl/lib/python3.9/site-packages/peft/mapping.py", line 90, in get_peft_model
peft_config.base_model_name_or_path = model.dict.get("name_or_path", None)
AttributeError: 'NoneType' object has no attribute 'base_model_name_or_path'

**Comment by Addss-s** [comment]
> Please provide more details
Traceback (most recent call last):
File "/home/lias/OpenFedLLM-main/main_dpo.py", line 61, in
model = get_peft_model(model, peft_config)
File "/home/lias/yes/envs/opfl/lib/python3.9/site-packages/peft/mapping.py", line 90, in get_peft_model
peft_config.base_model_name_or_path = model.dict.get("name_or_path", None)
AttributeError: 'NoneType' object has no attribute 'base_model_name_or_path'

**Comment by rui-ye** [comment]
Have you downloaded the base model (e.g., llama2-7b) and correctly put its path into the config?

**Comment by Addss-s** [comment]
The model is automatically downloaded from HuggingFace and downloaded to the default path of HuggingFace. Do I need to change it in the code?

**Comment by Addss-s** [comment]
Hello! I tried running the model separately and it was able to display the configuration of the model, but every time I executed the code model=get_peft_model (model, pekt_config), it couldn't load correctly. Still the same error file "/home/lias/OpenFedLLM main/main_depo. py", line 61, in
model = get_peft_model(model, peft_config)
File "/home/lias/yes/envs/opfl/lib/python3.9/site-packages/peft/mapping.py", line 90, in get_peft_model
peft_config.base_model_name_or_path = model.dict.get("name_or_path", None)
AttributeError: 'NoneType' object has no attribute 'base_model_name_or_path'

**Comment by Addss-s** [comment]
PEF==0.4.0 is also correctly installed

**Comment by rui-ye** [comment]
> Hello! I tried running the model separately and it was able to display the configuration of the model, but every time I executed the code model=get_peft_model (model, pekt_config), it couldn't load correctly. Still the same error file "/home/lias/OpenFedLLM main/main_depo. py", line 61, in model = get_peft_model(model, peft_config) File "/home/lias/yes/envs/opfl/lib/python3.9/site-packages/peft/mapping.py", line 90, in get_peft_model peft_config.base_model_name_or_path = model.dict.get("name_or_path", None) AttributeError: 'NoneType' object has no attribute 'base_model_name_or_path'

It seems like your `left_config` is None. Could you check for that? We did not get such error before.
